# Generated by Django 4.0.4 on 2022-06-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_romm_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='value',
            new_name='body',
        ),
    ]
