# Generated by Django 4.0.4 on 2022-05-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Romm',
            new_name='Room',
        ),
    ]
